language: node_js
node_js: "10"
install: npm ci
script:
    - npm test
    - npm build
    - ./scripts/update.sh
deploy:
    - provider: script
      skip_cleanup: true
      script: ./scripts/publish.sh
      on:
          branch: master
          condition: $TRAVIS_EVENT_TYPE != cron
