jobs:
    include:
        - stage: Pull Request Build and Test
          if: type = pull_request
          language: node_js
          node_js: '10'
          script:
              - npm test
              - npm build

        - stage: Build, Test, and Publish
          if: type != pull_request AND branch = master AND env(TRAVIS_EVENT_TYPE) != cron
          language: node_js
          node_js: '10'
          script:
              - npm test
              - npm build
              - ./scripts/publish.sh

        - stage: Automated Dependency Upgrade
          if: type != pull_request AND branch = master AND env(TRAVIS_EVENT_TYPE) = cron
          language: node_js
          node_js: '10'
          script:
              - ./scripts/update.sh
